#!/usr/bin/env bash
configdir=${PWD}
cd ~
if [ -L .vim ];
then
  rm .vim
fi

if [ -L .vimrc ];
then
  rm .vimrc
fi

if [ -L .ideavimrc ];
then
  rm .ideavimrc
fi

if [ -e .vim ];
then
  mkdir .old > /dev/null
  mv .vim .old
fi

if [ -e .vimrc ];
then
  mkdir .old > /dev/null
  mv .vimrc .old
fi

if [ -e .ideavimrc ];
then
  mkdir .old > /dev/null
  mv .ideavimrc .old
fi

ln -s ${configdir}/vim .vim
ln -s ${configdir}/vimrc .vimrc
ln -s ${configdir}/ideavimrc .ideavimrc

